# Source: https://medium.com/@krishnaregmi/wait-for-it-docker-compose-f0bac30f3357

version: '3'
services:
  db:
    image: mongo
    restart: unless-stopped
    env_file:
      - .envs/.db
    volumes:
      - db_data:/data/db
      - ./compose/db_init.js:/docker-entrypoint-initdb.d/db_init.js
  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=db
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mongoadmin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=secret
    depends_on:
      - db
  api:
    build:
      context: .
      dockerfile: compose/Dockerfile
    image: lightweight-netflix
    env_file:
      - .envs/.db
      - .envs/.api
    depends_on:
      - db
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
    ports:
      - "8080:8080"
      - "40000:40000"
    command: dlv debug --headless --listen=:40000 --api-version=2 --accept-multiclient ./cmd/server

volumes:
  db_data: